In [1]:
pip install numpy


In [2]:
import numpy as np

In [3]:
print("hello world")

hello world


In [5]:
#difference between python list and numpy array
python_list=[1,2,3,4,5]
print(python_list)

import numpy as np
numpy_array= np.array([6,7,8,9,10])
print(numpy_array)

[1, 2, 3, 4, 5]
[ 6  7  8  9 10]


In [11]:
#creation of array with default values

#zero value array
#np.zeros(shape)   (3) for 1d array and ((3,3)) for 2d array
print("zero array")
zero_arr= np.zeros(3)
print(zero_arr)

zero_arr_2d= np.zeros((3,4))
print(zero_arr_2d)


#ones(shape)
print("ones array")
ones_arr= np.ones((3,2))
print(ones_arr)


#for specific values : full function
#full(shape,value)
print("full function")
arr = np.full((3,2),78)
print(arr)

zero array
[0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array
[[1. 1.]
 [1. 1.]
 [1. 1.]]
full function
[[78 78]
 [78 78]
 [78 78]]


In [13]:
#creating sequence of numbers
#arange function
#arange(start,stop,step)
print("sequence of numbers")
range = np.arange(1,20,3)
print(range)

sequence of numbers
[ 1  4  7 10 13 16 19]


In [16]:
#creatig identity matrix
#eye function
#eye(size)
print("identity matrix")
identity = np.eye(2)
id2 = np.eye(3)
id3 = np.eye(4)

print("size:2",identity)
print("size:3",id2)
print("size:4",id3)

identity matrix
size:2 [[1. 0.]
 [0. 1.]]
size:3 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
size:4 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
